### ISSUE TITLE
Open music files with "Share" option

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/DialogMusicPlayer#11]
> However, trying to share a MP3 file, the app does not show up as target (my bad, it wasn't supposed to – might be a nice idea to enable that as well).

Feature request for show DMP as target app & play music files with "share to" as suggested
[here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10419#note_814165706) by @IzzySoft

**Comment by IzzySoft** [comment]
Thanks! Let me add the reason for that suggestion: I guess many users will, like me, try "share" first and wonder why DMP does not show up – until, slightly confused, they read the app description once more, :man_facepalming: face-palm, and use open-with :bulb:. Having DMP respond to "share" saves them/us a few slaps on the forehead :smile:
