### ISSUE TITLE
Slider jumps back upon seek

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/DialogMusicPlayer#13]
**Describe the bug**
DMP music bar isn't smooth as expected.

**To Reproduce**
1. play any music
2. click on pause
3. check the music pointer closely
4. play the music

Why it jumps little bit backwards? Possible to make it smooth?

**Additional context**

https://user-images.githubusercontent.com/48226312/150646769-374a7142-abf1-4347-82ce-bcfda13b1257.mp4

**Comment by VishnuSanal** [comment]
@shuvashish76 this too seems to be fixed with the latest release [v2.0.0](https://github.com/VishnuSanal/DialogMusicPlayer/releases/tag/v2.0.0) (set the slider to get updated every 10 milliseconds), please reopen if it is not the case :)
