### ISSUE TITLE
Crash on app startup

### ISSUE THREAD

**Issue by Sergei-Alekseev** [VishnuSanal/DialogMusicPlayer#17]
**Describe the bug**
Player doesn't start. 

**To Reproduce**
Open sound file with subj from fileman (TC)

**Expected behavior**
Player starts and play sound file

**Screenshots**
![Screenshot_20220204-104138](https://user-images.githubusercontent.com/28693250/152493852-19318952-1e0b-4ff5-aa91-6658a138e45c.png)
.

**Smartphone (please complete the following information):**
 - Device: Fly FS526 Power Plus 2
 - Andorid Version: 7.0

**Comment by Sergei-Alekseev** [comment]
Device Redmi 5+.
Nothing happens at all, even no close dialog.

**Comment by VishnuSanal** [comment]
@Sergei-Alekseev Thanks for reaching out! I am sorry to hear you bumped into problems. Would it be possible to get me the logs so that I can diagnose what exactly is causing this crash? Meanwhile I'll try reproducing the error from my side too. :)

**Comment by Sergei-Alekseev** [comment]
[data_app_crash@1643974299485.txt](https://github.com/VishnuSanal/DialogMusicPlayer/files/8002658/data_app_crash%401643974299485.txt)
Is it okay?

**Comment by VishnuSanal** [comment]
> Is it okay?

Yes, thanks! :)

**Comment by VishnuSanal** [comment]
Fixed with 80baf98
