### ISSUE TITLE
FR: controls in the notification area

### ISSUE THREAD

**Issue by foldfree** [VishnuSanal/DialogMusicPlayer#22]
**Is your feature request related to a problem? Please describe.**

Quick access to the player when multitasking.

**Describe the solution you'd like**

Have title of audio file, play/pause in the notification area like a regular audio player.

**Comment by VishnuSanal** [comment]
@foldfree fixed with the latest release [v2.0.0](https://github.com/VishnuSanal/DialogMusicPlayer/releases/tag/v2.0.0), please reopen if it is not the case :)
