### ISSUE TITLE
FR: save position on quit

### ISSUE THREAD

**Issue by foldfree** [VishnuSanal/DialogMusicPlayer#23]
**Is your feature request related to a problem? Please describe.**

DialogMusicPlayer is very useful for listening to long audio files pulled from YouTube/SoundCloud/etc for me. it would be very nice to have an option for it to behave like a podcast app player. like `mpv --save-position-on-quit` option.

**Describe the solution you'd like**

I know that checkbox might detract from the minimalism of the player and clutter the UI, maybe hidden behind a 3 dot menu?

**Comment by VishnuSanal** [comment]
> DialogMusicPlayer is very useful for listening to long audio files pulled from YouTube/SoundCloud/etc for me. it would be very nice to have an option for it to behave like a podcast app player. like `mpv --save-position-on-quit` option.

Agreed, it would be useful for listening to audio books too.

> I know that checkbox might detract from the minimalism of the player and clutter the UI, maybe hidden behind a 3 dot menu?

Checkbox? Three dot menu? I'm thinking about remembering the playback time for every unfinished music files played that are longer that a certain threshold (say 5 minutes) without bringing about any changes to the UI/UX. What say @foldfree?

Inviting the opinions of @shuvashish76 too :)

**Comment by VishnuSanal** [comment]
Currently save position

**Comment by VishnuSanal** [comment]
As of not, save position is remembered for audio files that are longer than 5 minutes. Should that be extended to **all** music files?

**Comment by VishnuSanal** [comment]
@VishnuSanal @foldtree @shuvashish76 @AyushIyankan @tsjazil

**Comment by VishnuSanal** [comment]
> As of not, save position is remembered for audio files that are longer than 5 minutes. Should that be extended to **all** music files? 

@foldfree @shuvashish76 @AyushIyankan @tsjazil

**Comment by AyushIyankan** [comment]
> 
Nope. But maybe the threshold needs to be reduced to 4 or 3min 30sec. Below the threshold there isn't a need for remembering, since one can easily seek second by second in the given screen width. So yeah, option to remember audio > 3min 30sec can be a good feature!

**Comment by VishnuSanal** [comment]
@VishnuSanal I think we can go with remembering save position for *all* files. We need not impose any restriction & the user can easily seek to the beginning if needed.
