### ISSUE TITLE
Album art implementation

### ISSUE THREAD

**Issue by AyushIyankan** [VishnuSanal/DialogMusicPlayer#26]
**UI Changes**
Change DMP UI background from plain color to album art derived from metadata of audio file.

**Other case**
If DMP can't parse appropriate album art from a selected audio file set DMP UI to a custom skin ( next feature request ) or revert to the default color.

**Suggestions / Reference**
Google music player UI for Android 13 ( currently only available in Notification Player ) can be taken as a reference.

Further , the background can be applied vignette for UI enhancement. Also splash effect or User Interaction with DMP can be implemented. ( strictly optional )

**Comment by VishnuSanal** [comment]
@AyushIyankan I think this can be closed now since DMP currently supports album art implementation.
