### ISSUE TITLE
Play multiple songs as playlist

### ISSUE THREAD

**Issue by asadise** [VishnuSanal/DialogMusicPlayer#32]
Can you please provide a way to share multiple songs (for example two mp3 files) via  **Share...** menu that DMP play shared songs as a playlist?
In other words, I select some mp3 and **Share via DialogMusicPlayer**, then DMP plays these songs as a playlist, this feature will be very cool.

**Comment by VishnuSanal** [comment]
Hi @asadise, thanks for reaching out!

We started off as a simple music player dialog - which is **only** intended to play a single audio file at a time. We have made design choices supporting the same too (for instance, placing the seek/rewind buttons on either side of the play/pause button where next/previous buttons usually reside).

So, for now, I think this feature should go to the backstage. We will definitely look into this feature request once it becomes feasible for DMP.

Inviting the opinions of @AyushIyankan @tsjazil & @shuvashish76 into this.
