### ISSUE TITLE
Support for headset pause button

### ISSUE THREAD

**Issue by Friptick** [VishnuSanal/DialogMusicPlayer#36]
**Is your feature request related to a problem? Please describe.**
Audio doesn't pause when wired headset button is pressed. 

**Describe the solution you'd like**
Implement basic support for the button.

Thanks for considering, and for your excellent work.

**Comment by VishnuSanal** [comment]
fixed with the latest release [v2.0.0](https://github.com/VishnuSanal/DialogMusicPlayer/releases/tag/v2.0.0), please reopen if it is not the case :)

**Comment by Friptick** [comment]
Great news! Thanks for your work Vishnu.
