### ISSUE TITLE
Crashes when play from Termux

### ISSUE THREAD

**Issue by luisadha** [VishnuSanal/DialogMusicPlayer#37]
<img src="https://user-images.githubusercontent.com/40796508/236732180-0b3ee67f-0c2d-4b70-b23a-a3ad5e8b4ea2.jpg" height=800 /> <img src="https://user-images.githubusercontent.com/40796508/236732583-6cc90719-9fb0-4b5a-ac82-275f2f0e19ac.jpg" height=800 />

**Expected behavior**
Should be like the second image
**Crash logs**
If possible, add crash logs to help us figure out the problem.

**Smartphone (please complete the following information):**
 - Device: Redmi 10 C (fog)
 - Andorid Version:  Android 11
 - App Version: latest from f-droid

**Additional context**
problem play with termux

**Comment by VishnuSanal** [comment]
@luisadha Hi, thanks for reaching out! I am sorry to hear you bumped into problems. From the Toast message in the screenshot provided, it looks like an issue with storage permission. Please verify that the read external storage permission is granted to DMP. Meanwhile I'll try reproducing the error from my side too. :)

**Comment by luisadha** [comment]
![Screenshot_2023-05-10-22-34-16-198_com google android permissioncontroller](https://github.com/VishnuSanal/DialogMusicPlayer/assets/40796508/f04754b4-7dc7-4cb7-8c92-1f8aec2f3b9a)

i think wrong permission, should be permission to file or change system setting? In images permission is requested for images and media. Cmiiw

**Comment by luisadha** [comment]
I usually use size utilities or sometimes use the default Xiaomi music player application. I'm just trying to use this app🙂

**Comment by VishnuSanal** [comment]
> i think wrong permission, should be permission to file or change system setting? In images permission is requested for images and media. Cmiiw

yeah, the name of the permission is `android.permission.READ_EXTERNAL_STORAGE` & Android shows it as images & media (since I presume it would make more sense to a common user). DMP basically wants access to read the storage (to access the music file being played), it's just that Android uses wordings like "images" & "media" to prompt to the user.

> I usually use size utilities or sometimes use the default Xiaomi music player application. I'm just trying to use this app

thank you & much appreciated that you took the effort to try use DMP, to try match it to your usecase & report back the stumbling blocks you faced meanwhile to me :)

thanks again, try granting the permission & please LMK whether that fixes the issue

**Comment by VishnuSanal** [comment]
> I found a solution. After seeing a comparison of 2 similar applications the dmp application does not include permissions to all files while the other apps includes 2 permissions namely images and media and all file

yeah, we do not really need the "all files permission", it is requesting access to the whole storage -- applications like file managers would need that.

**Comment by luisadha** [comment]
so are you going to add that permission? Or let DMP run like that

**Comment by luisadha** [comment]
> 

Saya memverifikasi ini sama seperti punya saya.

**Comment by luisadha** [comment]
Good job guys the app is as expected, but is it running in the background? When I touch the part outside the DMP box/popup the app does not close if I touch the Quit button then the music stops as well as when I press the back button.

Did you forget to give support permission
[Display on top of other apps].

Thank you for your attention
Diterjemahkan dengan DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by luisadha** [comment]
@VishnuSanal Because I see other 2 music player apps on my device need those special permissions

**Comment by luisadha** [comment]
@VishnuSanal i'm fix this by bash my function "hide_soft_keyboard"

Please keep the application even if the soft keyboard is open

**Comment by luisadha** [comment]
reopen this issue please

**Comment by VishnuSanal** [comment]
@luisadha I didn't quite get you; what is the current issue that you are facing?

**Comment by luisadha** [comment]
### 

> @luisadha I didn't quite get you; what is the current issue that you are facing?

I mean, the app window disappears when the smartphone keyboard is idle (IME), it causes the app can't play the requested song via xdg-open

**Comment by luisadha** [comment]
> @luisadha I didn't quite get you; what is the current issue that you are facing?

My project relies on apps like yours so I hope the app side of this issue can be resolved so I don't write "hide_soft_keyboard" in my project. Sorry for the trouble

**Comment by VishnuSanal** [comment]
@luisadha please create a new issue.
