### ISSUE TITLE
Play m3u/m3u8 files

### ISSUE THREAD

**Issue by asadise** [VishnuSanal/DialogMusicPlayer#38]
Please adding a feature for playing [m3u/m3u8](https://en.wikipedia.org/wiki/M3U) files, It may contain URL or local (relative/absolute) paths.

**Comment by VishnuSanal** [comment]
> Please adding a feature for playing [m3u/m3u8](https://en.wikipedia.org/wiki/M3U) files, It may contain URL or local (relative/absolute) paths.

M3U/M3U8 files seems like a file containing playlist information. we are just playing a single file & are not planning to support playlists as of now.

(or am I missing something here? feel free to re-open, if that is the case)
