### ISSUE TITLE
Why dialog window ?

### ISSUE THREAD

**Issue by Cwpute** [VishnuSanal/DialogMusicPlayer#39]
I guess this is more a discussion than a feature request.

Why the choice of a dialog window ?

I realy like the app, but i don't get why you'd embed the player into a faked dialog window. i say faked because it cant be moved around, and serves no particular purpose as far as i can tell.
Why not have the dialog window take the entire screen space then ? you wpuld have more space for buttons, file title and all.
And couldn't it play in the background from the drop-down menu, like other players ? This way you'd get rid of the diulog window and let the player do its thing in the bakground without even having to deal with the dialog window.

**Comment by VishnuSanal** [comment]
> Why the choice of a dialog window ?
> I realy like the app, but i don't get why you'd embed the player into a faked dialog window. i say faked because it cant be moved around, and serves no particular purpose as far as i can tell.

Hi, thanks for reaching out + for the nice words! The whole point of DMP was to serve the same purpose of the built-in music player that came with my smartphone by default, but it had unnecessary permisions n stuff. You can find the story in the [first release page](https://github.com/VishnuSanal/DialogMusicPlayer/releases/tag/v1.0.0).

> Why not have the dialog window take the entire screen space then ? you wpuld have more space for buttons, file title and all.

The point in using our application was to play an audio file from a file manager or listen to podcasts/audiobooks etc. We need not cover the whole screen for I want DMP to be lightweight in the domain of performance as well as usability & visual appearance.

> And couldn't it play in the background from the drop-down menu, like other players ? This way you'd get rid of the diulog window and let the player do its thing in the bakground without even having to deal with the dialog window.

Yess! The works of integrating DMP with Android's `MediaSession` for background playback along with a notification for playback controls is in the works & I expect to complete it soon! :)

PS: I am busy with my exams these days, sorry for the delay in giving a reply.

**Comment by Cwpute** [comment]
> We need not cover the whole screen for I want DMP to be lightweight in the domain of performance as well as usability & visual appearance.

I didn't know using the whole screen instead wf a small window would make for worse perfwrmance, if anything, i thought it would be the contrary!

As fwr utability, as i said, a smaller window would allow for more possible actions, buttons, and informations, but if the main point is performance, this may not be the best idea then.

**Comment by VishnuSanal** [comment]
> > We need not cover the whole screen for I want DMP to be lightweight in the domain of performance as well as usability & visual appearance.
> 
> I didn't know using the whole screen instead wf a small window would make for worse perfwrmance, if anything, i thought it would be the contrary!
> 
> As fwr utability, as i said, a smaller window would allow for more possible actions, buttons, and informations, but if the main point is performance, this may not be the best idea then.

no! I just meant that a dialog uses little screen space & thereby minimal. sorry for not making this clear in my previous text.

as mentioned before an update is in progress that would bring in notification playback; hopefully the problems mentioned in this issue can be resolved by that :)

> PS: I am busy with my exams these days, sorry for the delay in giving a reply.

**Comment by VishnuSanal** [comment]
@Cwpute as mentioned before, the issues you were facing must be fixed with the addtion of a notification on the latest release v2.0.0 (https://github.com/VishnuSanal/DialogMusicPlayer/releases/tag/v2.0.0), please reopen the issue if it is not the case :)

**Comment by luisadha** [comment]
> I guess this is more a discussion than a feature request.
> 
> Why the choice of a dialog window ?
> 
> I realy like the app, but i don't get why you'd embed the player into a faked dialog window. i say faked because it cant be moved around, and serves no particular purpose as far as i can tell. Why not have the dialog window take the entire screen space then ? you wpuld have more space for buttons, file title and all. And couldn't it play in the background from the drop-down menu, like other players ? This way you'd get rid of the diulog window and let the player do its thing in the bakground without even having to deal with the dialog window.

i like this feature, don't changes
