### ISSUE TITLE
Crash on pause and opening new file

### ISSUE THREAD

**Issue by Cwpute** [VishnuSanal/DialogMusicPlayer#48]
**Describe the bug**
When dmp is already open and paused in the background, if you try to open a new file with it from any app, it takes two attempts to play a sound file.
The first attempt does nothing (or maybe it silently crashes the player), and the second attempt actually starts playing the file. If you try to bring dmp in focus after the first attempt, it will attempt to play the previous file as if you didn't tell it to before, and will not take into account the file you just asked it to open.
After several attempts trying to reproduce this bug, dmp even triggered a crash warning saying "DMP keeps crashing/systematically crashes." (see screenshot)
![Screenshot_20230918-003948](https://github.com/VishnuSanal/DialogMusicPlayer/assets/80604512/ea7ef49a-bfd4-4091-9d64-af65b8ef59e4)

**To Reproduce**
1. Open a file with DMP
2. Pause DMP
3. Focus on another app wuthout closing DMP
4. Try to open a new file with DMP

**Expected behavior**
DMP should open the file on the first attempt.

**Smartphone (please complete the following information):**
 - Device: Nokia TA-1157
 - Andorid Version: 11
 - App Version: 2.1.0 and 2.1.1

**Additional context**
Similar problems seem to have been reported and solved for 2.1.0 —namely https://github.com/VishnuSanal/DialogMusicPlayer/issues/44 and https://github.com/VishnuSanal/DialogMusicPlayer/issues/43 — but i downloaded and tested the apk for 2.1.1 and the problem persisted.

**Comment by VishnuSanal** [comment]
@Cwpute Thanks for reaching out! I am sorry to hear you bumped into problems. Maybe you're facing #47 (which wasn't rolled with v2.1.1) 🤔 Do you mind fetching the crash report?

**Comment by Cwpute** [comment]
Ah shoot didn't see this one issue. Where should i get the crash report at ?

**Comment by VishnuSanal** [comment]
@Cwpute Um... Please try whether you can extract the crash reports from LogFox https://www.f-droid.org/packages/com.f0x1d.logfox/ . Please LMK if you can't, I'll send a debug APK built with the latest code.

**Comment by Cwpute** [comment]
Oh logcats... last time i tried there were several hurddles i tried to get over but... i got lost in the instructions... you need to enable a bunch of things and i think i couldn't make Android Studio to work on my 32bit machine or something.
I'm gonna pass this one and try the debug APK instead yeah :/

**Comment by VishnuSanal** [comment]
@Cwpute [app-debug.zip](https://github.com/VishnuSanal/DialogMusicPlayer/files/12664093/app-debug.zip)

**Comment by Cwpute** [comment]
Ok it seems to work! no more needing to tap several times on files to open them :)
thanks!

**Comment by VishnuSanal** [comment]
> Ok it seems to work! no more needing to tap several times on files to open them :) thanks!

great, happy to hear! thanks for testing :) (if you wish, you can leave the nice words in the wall of love (#28) too)
