### ISSUE TITLE
typo in the bug report template

### ISSUE THREAD

**Issue by sameemul-haque** [VishnuSanal/DialogMusicPlayer#52]
There is a typo in the bug report template in the Smartphone section. "And**or**id Version" should be corrected to "And**ro**id Version"

![typo](https://github.com/VishnuSanal/DialogMusicPlayer/assets/110324374/e97fbe36-4cca-46f7-be9c-506943807634)

**Comment by VishnuSanal** [comment]
Fixed with #53
