### ISSUE TITLE
App doesn't appear on Phone when trying to download

### ISSUE THREAD

**Issue by SunBreaker1** [VishnuSanal/DialogMusicPlayer#54]
Samsung S23+
Android 13

Tried to download off of Github and Fdroid
Says they downloaded, however, app doesn't appear in app tray or on home screen.

But, it appears in apps on phone in the settings.

Either way, I am unable to find and launch the app after downloading it.

**Comment by VishnuSanal** [comment]
> Do not be irritated if you don't find a launcher icon: there currently is none. The app accepts music files to play via the "open with" menu or from the "share to" menu of Android, e.g. via a file manager, other utility apps etc. And as it has no icon in the launcher: should you ever want to uninstall it, you'll have to do that via Android's Settings › Apps menu (or via the „market app“ you used to install it).

there is no launcher icon for DMP!
