### ISSUE TITLE
does not support opus

### ISSUE THREAD

**Issue by n-ce** [VishnuSanal/DialogMusicPlayer#57]
**Describe the bug**
Cannot play .opus files

**Expected behavior**
Supports opus files

**Smartphone (please complete the following information):**
 - Device: Samsung
 - Android Version: Android 10
 - App Version: v2.1.2

**Comment by VishnuSanal** [comment]
@n-ce thanks for reaching out! this is weird since DMP does support OPUS files. I tried with an OPUS file right now & it played seamlessly. please verify the file you were trying to play was not corrupted.

**Comment by n-ce** [comment]
Yes

> @n-ce thanks for reaching out! this is weird since DMP does support OPUS files. I tried with an OPUS file right now & it played seamlessly. please verify the file you were trying to play was not corrupted.

It seems that It's a problem with the samsung file manager.
