### ISSUE TITLE
Folder based playlist support

### ISSUE THREAD

**Issue by kaafir786** [VishnuSanal/DialogMusicPlayer#60]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to stop my music to play another from folder.

**Describe the solution you'd like**
Basically when I start a music from a folder add all other music files in queue and give basic options like back forward and Repeat.

**Describe alternatives you've considered**
Not applicable this is most basic thought I have.

**Additional context**
Quite understandable so I guess not applicable.

Let me know of any other help I can make.

Offtopic : Namaskaram Vishnu Deva

**Comment by VishnuSanal** [comment]
hi, thanks for reaching out! this completely overrules the purpose DMP was built on top of! ref #32 for more details. thanks! :)
