### ISSUE TITLE
Crash when playing a large file or a .flac

### ISSUE THREAD

**Issue by yephny** [VishnuSanal/DialogMusicPlayer#9]
**Describe the bug**
App crashes when playing a large file (or it could be about .flac files, I'm not sure).

**To Reproduce**
1. Play a file that's at least 50 MB. Try out a .flac as well.

**Smartphone**
- Android 10, app v.1.0.1

**Comment by VishnuSanal** [comment]
Thanks for reporting, will look into it.

**Comment by VishnuSanal** [comment]
I tried opening an FLAC file on ~70MB, it worked okay.

Also, I tried ~0.5GB MP3, that too _worked_ - had to wait for a while to get that loaded though, let me see a solution for this.

Meanwhile @yephny can you confirm the specifics of this issue? Thanks!

**Comment by yephny** [comment]
Testing it again, the file is apparently corrupted. Strange that it wasn't, before.

**Comment by VishnuSanal** [comment]
> Testing it again, the file is apparently corrupted. Strange that it wasn't before.

@yephny Oh okay. But crashing is not at all a good UX! Can you have please get me the logs if you can? Thanks!

**Comment by yephny** [comment]
https://ix.io/3M89

**Comment by VishnuSanal** [comment]
> https://ix.io/3M89

Thanks!

```
FATAL EXCEPTION: Timer-0
Process: phone.vishnu.dialogmusicplayer, PID: 23763
java.lang.IllegalStateException
at android.media.MediaPlayer.getCurrentPosition(Native Method)
at phone.vishnu.dialogmusicplayer.MainActivity$a.run(:3)
at java.util.TimerThread.mainLoop(Timer.java:562)
at java.util.TimerThread.run(Timer.java:512)
```

Posting here too for reference. Seems like it's the same as #1
